<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Learning\Taxonomy\Controller\CategoryController'          => __DIR__ . '/Controller/CategoryController.php',
    'Learning\Taxonomy\EventManager\InjectTemplateListener'    => __DIR__ . '/EventManager/InjectTemplateListener.php',
    'Learning\Taxonomy\Factory\Form\CreateCategoryFormFactory' => __DIR__ . '/Factory/Form/CreateCategoryFormFactory.php',
    'Learning\Taxonomy\Factory\Service\CategoryServiceFactory' => __DIR__ . '/Factory/Service/CategoryServiceFactory.php',
    'Learning\Taxonomy\Form\TaxonomyForm'                      => __DIR__ . '/Form/TaxonomyForm.php',
    'Learning\Taxonomy\Hydrator\AggregateHydrator'             => __DIR__ . '/Hydrator/AggregateHydrator.php',
    'Learning\Taxonomy\InputFilter\InputFilter'                => __DIR__ . '/InputFilter/InputFilter.php',
    'Learning\Taxonomy\Service\CategoryService'                => __DIR__ . '/Service/CategoryService.php',
);
