<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Agent\Hydrator\AggregateHydrator'                 => __DIR__ . '/Hydrator/AggregateHydrator.php',
    'Agent\Form\Initializer'                           => __DIR__ . '/Form/Initializer.php',
    'Agent\Form\AgentForm'                             => __DIR__ . '/Form/AgentForm.php',
    'Agent\Service\AgentService'                       => __DIR__ . '/Service/AgentService.php',
    'Agent\View\Helper\GetAgencyName'                  => __DIR__ . '/View/Helper/GetAgencyName.php',
    'Agent\InputFilter\Agent'                          => __DIR__ . '/InputFilter/Agent.php',
    'Agent\Controller\ManageController'                => __DIR__ . '/Controller/ManageController.php',
    'Agent\Module'                                     => __DIR__ . '/Module.php',
    'Agent\EventManager\Listener\RouteListener'        => __DIR__ . '/EventManager/Listener/RouteListener.php',
    'Agent\Factory\Form\NewFormFactory'                => __DIR__ . '/Factory/Form/NewFormFactory.php',
    'Agent\Factory\Form\EditFormFactory'               => __DIR__ . '/Factory/Form/EditFormFactory.php',
    'Agent\Factory\Service\AgentServiceFactory'        => __DIR__ . '/Factory/Service/AgentServiceFactory.php',
    'Agent\Factory\Service\AgentAllServiceFactory'     => __DIR__ . '/Factory/Service/AgentAllServiceFactory.php',
    'Agent\Factory\View\Helper\AgentViewHelperFactory' => __DIR__ . '/Factory/View/Helper/AgentViewHelperFactory.php',
);
