<?php
/**
 * Generated by ZF2's ./bin/classmap_generator.php
 *  @copyright  Copyright (c) 2012 Savv-e.com.au
 * @category : Zend
 */
spl_autoload_register(include __DIR__ . '/autoload_function.php');
