<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Company\Controller\ManageController'                 => __DIR__ . '/Controller/ManageController.php',
    'Company\Doctrine\Event\Subscriber'                   => __DIR__ . '/Doctrine/Event/Subscriber.php',
    'Company\Event\Event'                                 => __DIR__ . '/Event/Event.php',
    'Company\Event\ListenerAggregate'                     => __DIR__ . '/Event/ListenerAggregate.php',
    'Company\Factory\Form\EditFormFactory'                => __DIR__ . '/Factory/Form/EditFormFactory.php',
    'Company\Factory\Form\NewFormFactory'                 => __DIR__ . '/Factory/Form/NewFormFactory.php',
    'Company\Factory\Service\CompanyAllServiceFactory'    => __DIR__ . '/Factory/Service/CompanyAllServiceFactory.php',
    'Company\Factory\Service\CompanyDataServiceFactory'   => __DIR__ . '/Factory/Service/CompanyDataServiceFactory.php',
    'Company\Factory\Service\CompanyEntityServiceFactory' => __DIR__ . '/Factory/Service/CompanyEntityServiceFactory.php',
    'Company\Factory\Service\CompanyServiceFactory'       => __DIR__ . '/Factory/Service/CompanyServiceFactory.php',
    'Company\Form\CompanyForm'                            => __DIR__ . '/Form/CompanyForm.php',
    'Company\Form\Initializer'                            => __DIR__ . '/Form/Initializer.php',
    'Company\Hydrator\AggregateHydrator'                  => __DIR__ . '/Hydrator/AggregateHydrator.php',
    'Company\InputFilter\Company'                         => __DIR__ . '/InputFilter/Company.php',
    'Company\Module'                                      => __DIR__ . '/Module.php',
    'Company\Service\CompanyService'                      => __DIR__ . '/Service/CompanyService.php',
);
